Repository Final-DAMDA/BE_DAMDA, pull requests merged in 2023-06, with the labels that each got.

#14 Manager application form
  .idea/JetClient/state.xml
  .idea/aws.xml
  .idea/compiler.xml
  .idea/jarRepositories.xml
  back/src/main/java/com/damda/back/domain/area/Area.java
  back/src/main/java/com/damda/back/domain/area/AreaEnum.java
  back/src/main/java/com/damda/back/domain/area/AreaEnumExt.java
  back/src/main/java/com/damda/back/domain/area/AreaEnumGroup.java
  back/src/main/java/com/damda/back/domain/area/CityEnum.java
  back/src/main/java/com/damda/back/domain/area/DistrictEnum.java
  back/src/main/java/com/damda/back/domain/manager/ActivityDay.java
  back/src/main/java/com/damda/back/domain/manager/AreaManger.java
  back/src/main/java/com/damda/back/domain/manager/CertificateStatus.java
  back/src/main/java/com/damda/back/domain/manager/Manager.java
  back/src/test/java/com/damda/back/BackApplicationTests.java
Labels: Category : DB

#15 Manager domain 수정
  .idea/compiler.xml
  .idea/misc.xml
  back/src/main/java/com/damda/back/controller/ManagerController.java
  back/src/main/java/com/damda/back/data/request/ManagerApplicationDTO.java
  back/src/main/java/com/damda/back/domain/area/Area.java
  back/src/main/java/com/damda/back/domain/area/CityEnum.java
  back/src/main/java/com/damda/back/domain/manager/ActivityDay.java
  back/src/main/java/com/damda/back/domain/manager/AreaManager.java
  back/src/main/java/com/damda/back/domain/manager/AreaManger.java
  back/src/main/java/com/damda/back/domain/manager/CertificateStatus.java
  back/src/main/java/com/damda/back/domain/manager/CertificateStatusEnum.java
  back/src/main/java/com/damda/back/domain/manager/Manager.java
  back/src/main/java/com/damda/back/repository/ActivityDayRepository.java
  back/src/main/java/com/damda/back/repository/AreaManagerRepository.java
  back/src/main/java/com/damda/back/repository/AreaRepository.java
  back/src/main/java/com/damda/back/repository/ManagerRepository.java
  back/src/main/java/com/damda/back/repository/custom/ActivityDayCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/AreaCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/AreaManagerCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/Impl/ActivityDayRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/Impl/AreaManagerRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/Impl/AreaRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/Impl/ManagerRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/ManagerCustomRepository.java
  back/src/main/java/com/damda/back/service/Impl/ManagerServiceImpl.java
  back/src/main/java/com/damda/back/service/ManagerService.java
  back/src/main/resources/application-dev.properties
  back/src/test/java/com/damda/back/domain/area/AreaEnumGroupTest.java
Labels: Category : DB

#31 Manager application form
  back/src/main/java/com/damda/back/data/request/ManagerApplicationDTO.java
  back/src/main/java/com/damda/back/domain/area/Area.java
  back/src/main/java/com/damda/back/domain/manager/ActivityDay.java
  back/src/main/java/com/damda/back/domain/manager/AreaManager.java
  back/src/main/java/com/damda/back/domain/manager/Manager.java
  back/src/main/java/com/damda/back/repository/custom/AreaCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/Impl/AreaRepositoryImpl.java
  back/src/main/java/com/damda/back/service/Impl/ManagerServiceImpl.java
  back/src/test/java/com/damda/back/repository/custom/Impl/AreaRepositoryImplTest.java
Labels: Category : DB

#39 Manager application form
  back/src/main/java/com/damda/back/controller/ManagerController.java
  back/src/main/java/com/damda/back/data/response/ManagerResponseDTO.java
  back/src/main/java/com/damda/back/domain/manager/Manager.java
  back/src/main/java/com/damda/back/repository/custom/Impl/ManagerRepositoryImpl.java
  back/src/main/java/com/damda/back/service/Impl/ManagerServiceImpl.java
  back/src/main/resources/application-dev.properties
  back/src/main/resources/application.properties
Labels: Category : DB

#40 FEAT: add previous manager status, current manager status
  back/src/main/java/com/damda/back/domain/manager/Manager.java
Labels: Category : DB

#43 FEAT: 알림톡 2개 완성, 할인 코드 구현완료
  back/build.gradle
  back/src/main/java/com/damda/back/BackApplication.java
  back/src/main/java/com/damda/back/config/CommonConfig.java
  back/src/main/java/com/damda/back/config/SolapiConfig.java
  back/src/main/java/com/damda/back/config/advice/GlobalRestAdvice.java
  back/src/main/java/com/damda/back/controller/FormController.java
  back/src/main/java/com/damda/back/controller/MemberController.java
  back/src/main/java/com/damda/back/controller/ReservationController.java
  back/src/main/java/com/damda/back/controller/TestController.java
  back/src/main/java/com/damda/back/data/common/QuestionIdentify.java
  back/src/main/java/com/damda/back/data/request/CustomerTalkDTO.java
  back/src/main/java/com/damda/back/data/request/FormStatusModifyRequestDTO.java
  back/src/main/java/com/damda/back/data/request/MatchingCompletedDTO.java
  back/src/main/java/com/damda/back/data/request/ResCompleteRequestDTO.java
  back/src/main/java/com/damda/back/data/response/FormSliceDTO.java
  back/src/main/java/com/damda/back/domain/DiscountCode.java
  back/src/main/java/com/damda/back/domain/Match.java
  back/src/main/java/com/damda/back/domain/Member.java
  back/src/main/java/com/damda/back/domain/ReservationSubmitForm.java
  back/src/main/java/com/damda/back/domain/area/Area.java
  back/src/main/java/com/damda/back/domain/manager/AreaManager.java
  back/src/main/java/com/damda/back/domain/manager/Manager.java
  back/src/main/java/com/damda/back/exception/ErrorCode.java
  back/src/main/java/com/damda/back/filter/AccessCheckFilter.java
  back/src/main/java/com/damda/back/repository/custom/AreaCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/Impl/AreaRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/Impl/ManagerRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/Impl/MatchRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/Impl/MemberRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/Impl/ReservationFormRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/ManagerCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/MatchCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/MemberCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/ReservationFormCustomRepository.java
  back/src/main/java/com/damda/back/service/CodeService.java
  back/src/main/java/com/damda/back/service/Impl/CodeServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/ReservationServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/SubmitServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/TalkSendServiceImpl.java
  back/src/main/java/com/damda/back/service/ReservationService.java
  back/src/main/java/com/damda/back/service/SubmitService.java
  back/src/main/java/com/damda/back/service/TalkSendService.java
  back/src/main/java/com/damda/back/utils/SolapiUtils.java
  back/src/main/resources/application-dev.properties
  back/src/main/resources/application-prod.properties
  back/src/test/java/com/damda/back/BackApplicationTests.java
Labels: Category : API, Category : DB

#56 Manager application form
  back/src/main/java/com/damda/back/controller/ManagerController.java
  back/src/main/java/com/damda/back/data/response/ManagerResponseDTO.java
  back/src/main/java/com/damda/back/repository/custom/AreaManagerCustomRepository.java
  back/src/main/java/com/damda/back/repository/custom/Impl/AreaManagerRepositoryImpl.java
  back/src/main/java/com/damda/back/repository/custom/Impl/AreaRepositoryImpl.java
  back/src/main/java/com/damda/back/service/Impl/ManagerServiceImpl.java
  back/src/main/java/com/damda/back/service/ManagerService.java
  back/src/main/resources/application-prod.properties
  back/src/main/resources/application.properties
Labels: Category : API, Category : DB

#69 Manager application form
  back/src/main/java/com/damda/back/config/InitQuery.java
  back/src/main/java/com/damda/back/controller/ManagerController.java
  back/src/main/java/com/damda/back/controller/QnAController.java
  back/src/main/java/com/damda/back/data/request/ManagerApplicationDTO.java
  back/src/main/java/com/damda/back/data/request/ManagerUpdateRequestDTO.java
  back/src/main/java/com/damda/back/data/request/QnARequestDTO.java
  back/src/main/java/com/damda/back/data/response/ManagerResponseDTO.java
  back/src/main/java/com/damda/back/data/response/ManagerUpdateResponseDTO.java
  back/src/main/java/com/damda/back/data/response/MatchingListDTO.java
  back/src/main/java/com/damda/back/domain/QnA.java
  back/src/main/java/com/damda/back/domain/manager/CertificateStatusEnum.java
  back/src/main/java/com/damda/back/domain/manager/Manager.java
  back/src/main/java/com/damda/back/domain/manager/ManagerStatusEnum.java
  back/src/main/java/com/damda/back/exception/ErrorCode.java
  back/src/main/java/com/damda/back/repository/custom/Impl/ManagerRepositoryImpl.java
  back/src/main/java/com/damda/back/service/Impl/ManagerServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/MatchServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/QnAServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/SubmitServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/TalkSendServiceImpl.java
  back/src/main/java/com/damda/back/service/QnAService.java
Labels: Category : API

#71 CHORE: change manager phone number
  back/src/main/java/com/damda/back/config/InitQuery.java
  back/src/main/java/com/damda/back/data/request/ManagerApplicationDTO.java
  back/src/main/java/com/damda/back/data/response/ManagerUpdateResponseDTO.java
  back/src/main/java/com/damda/back/data/response/MatchingListDTO.java
  back/src/main/java/com/damda/back/domain/manager/Manager.java
  back/src/main/java/com/damda/back/service/Impl/ManagerServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/SubmitServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/TalkSendServiceImpl.java
Labels: Category : API

#83 Manager application form
  back/src/main/java/com/damda/back/controller/ManagerController.java
  back/src/main/java/com/damda/back/controller/QnAController.java
  back/src/main/java/com/damda/back/data/response/ManagerResponseDTO.java
  back/src/main/java/com/damda/back/domain/manager/Manager.java
  back/src/main/java/com/damda/back/exception/ErrorCode.java
  back/src/main/java/com/damda/back/repository/custom/Impl/AreaRepositoryImpl.java
  back/src/main/java/com/damda/back/service/Impl/ManagerServiceImpl.java
  back/src/main/java/com/damda/back/service/Impl/QnAServiceImpl.java
Labels: Category : API

#99 Manager application form
  back/src/main/java/com/damda/back/config/InitQuery.java
  back/src/main/java/com/damda/back/domain/manager/CertificateStatusEnum.java
  back/src/main/java/com/damda/back/service/Impl/MatchServiceImpl.java
Labels: Category : API
